apiVersion: v1
kind: Service
metadata:
  labels:
    app: events-external-py
  name: events-external-py
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: events-external-py
  type: LoadBalancer
status:
  loadBalancer: {}