apiVersion: v1
kind: Service
metadata:
  labels:
    app: events-external-react
  name: events-external-react
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: events-external-react
  type: LoadBalancer
status:
  loadBalancer: {}